version: "3.9"

volumes:
  mysql_data:
networks:
  apache-db: {}
  react-apache: {}

services:
  mysql:
    container_name: MySQL
    image: mysql:8.1
    restart: always
    env_file:
      - .env.development
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d
    networks:
      - apache-db
    ports:
      - 9906:3306

  php-apache:
    container_name: php-apache
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env.development
    volumes:
      - ./backend/:/app/backend/
      - /var/www/html/backend/vendor
    networks:
      - apache-db
      - react-apache
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8000:80

  phpmyadmin:
    container_name: mysql-interface
    image: phpmyadmin:5
    restart: always
    environment:
      PMA_HOST: mysql
    networks:
      - apache-db
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8080:80

  frontend:
    container_name: frontend-vite
    build:
      context: ./vite
      dockerfile: Dockerfile
    env_file:
      - .env.development
    command: npm run dev
    volumes:
      - ./vite/:/app/vite
      - /app/vite/node_modules
    tty: true
    stdin_open: true
    environment:
      NODE_ENV: development
    networks:
      - react-apache
    depends_on:
      - php-apache
    ports:
      - "3000:3000"
